"""initial

Revision ID: f92e12f20e01
Revises: 
Create Date: 2026-05-13 17:25:00.142139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92e12f20e01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('verdict', sa.Enum('APPROVE', 'REQUEST_CHANGES', 'COMMENT', name='verdict_enum', create_constraint=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('files_reviewed', sa.JSON(), nullable=False),
    sa.Column('files_skipped', sa.JSON(), nullable=False),
    sa.Column('total_issues_posted', sa.Integer(), nullable=False),
    sa.Column('total_issues_filtered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_repo'), ['repo'], unique=False)

    op.create_table('filtered_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('issue_data', sa.Text(), nullable=False),
    sa.Column('filter_reason', sa.String(length=500), nullable=False),
    sa.Column('file', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filtered_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filtered_issues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filtered_issues_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtered_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filtered_issues_review_id'))
        batch_op.drop_index(batch_op.f('ix_filtered_issues_id'))

    op.drop_table('filtered_issues')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_repo'))
        batch_op.drop_index(batch_op.f('ix_reviews_job_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_id'))

    op.drop_table('reviews')

    # Drop the PostgreSQL enum type — autogenerate omits this, causing
    # "type already exists" errors if you downgrade and re-upgrade on PostgreSQL.
    # On SQLite this is a no-op (bind_processor handles it).
    op.execute("DROP TYPE IF EXISTS verdict_enum")
    # ### end Alembic commands ###
